# Discord: https://discord.gg/4bAceda9q3
# Github : https://github.com/ValresMC
# By ValresMC
#
#
messages:
  - "§1>§r Welcome to the server !"
  - "§1>§r Thanks to play on this server !"
  # Add as many messages as you want.

time: 300 # in seconds.